[versions]
# Plugins
kotlin = "2.3.10"
springBoot = "4.0.2"

# Libraries
jdbi = "3.51.0"
flyway = "12.0.0"
postgresql = "42.7.9"
kotlinLogging = "7.0.13"
ulid = "1.6.0"
pgEmbedded = "5.4.1"

[libraries]
# Platforms (BOMs)
jdbi-bom = { group = "org.jdbi", name = "jdbi3-bom", version.ref = "jdbi" }
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }

# Application Dependencies
# In build.gradle.kts, access these as: libs.spring.boot.starter.web
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }

# Database & Logic
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
ulid = { group = "com.aallam.ulid", name = "ulid-kotlin", version.ref = "ulid" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLogging" }

# JDBI Modules
jdbi-core = { group = "org.jdbi", name = "jdbi3-core" }
jdbi-spring = { group = "org.jdbi", name = "jdbi3-spring" }
jdbi-kotlin = { group = "org.jdbi", name = "jdbi3-kotlin" }
jdbi-kotlin-sqlobject = { group = "org.jdbi", name = "jdbi3-kotlin-sqlobject" }
jdbi-jackson2 = { group = "org.jdbi", name = "jdbi3-jackson2" }

# Testing
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
jdbi-testing = { group = "org.jdbi", name = "jdbi3-testing" }
pg-embedded = { group = "de.softwareforge.testing", name = "pg-embedded", version.ref = "pgEmbedded" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }

[bundles]
jdbi = [
    "jdbi-core",
    "jdbi-spring",
    "jdbi-kotlin",
    "jdbi-kotlin-sqlobject",
    "jdbi-jackson2"
]
flyway = [
    "flyway-core",
    "flyway-database-postgresql"
]
